spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mmall?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

# application.yml
mybatis-plus:
  mapper-locations: classpath:com/example/mapper/xml/*.xml
  type-aliases-package: com.example.entity
  configuration:
    map-underscore-to-camel-case: true
